### ISSUE TITLE
Проблема с ViewPager

### ISSUE THREAD

**Issue by ppzhuk** [CSC-MobDev-2016/lessson9#1]
Я добавил viewpager к приложению, который иногда работает нормально. Но периодически (при выборе города из списка или при свайпах вправо-влево) я получаю ошибку о том, что фрагмент не привязан к активити.

![default](https://cloud.githubusercontent.com/assets/10628180/15070283/8f434a78-1383-11e6-8921-c96f3417b4d1.PNG)

Ошибка происходит при вызове `textView.setText(getString(resource) + "some text")` в методе `renderForecast()`. Вероятно, это связано с тем, что viewpager периодически добавляет и удаляет фрагменты (я использую FragmentStatePagerAdapter), но я не понимаю, как это исправить. Я пробовал вызывать  `renderForecast()` внутри `onResume()` фрагмента, где активити уже однозначно должна быть привязана, но это ничего не дало.

Подскажите, в чем может быть проблема??

**Comment by thevery** [comment]
Без кода точно не скажу.
А там внутри не коллбэк-ли от асинктаска? А инстанс фрагмента один или много?

**Comment by ppzhuk** [comment]
Код активити, которая хостит ViewPager:
https://github.com/ppzhuk/lessson9/blob/master/app/src/main/java/ru/ppzh/weather/DetailsPagerActivity.java

Фрагмент, который возвращается VewPager:
https://github.com/ppzhuk/lessson9/blob/master/app/src/main/java/ru/ppzh/weather/WeatherFragment.java

Вообще, колбек от асинктаска, да. Взаимодействие в textView проходит в onPostExecute.. Когда до этого доходит дело, то фрагмент может уже быть отвязан от активити.. Я поправлю этот момент, но это не объясняет ошибки при выборе города из списка.

Насколько я знаю, ViewPager заранее подгружает один фрагмент слева и справа, итого 3 фрагмента. Но я не вижу с этим проблем.

**Comment by thevery** [comment]
> Я поправлю этот момент, но это не объясняет ошибки при выборе города из списка.

А какой стектрейс в этом случае?

**Comment by ppzhuk** [comment]
Такой же.

**Comment by thevery** [comment]
Совсем такой же не может быть, там же нет вызова AsyncTask-а.
У меня как-то сходу баг не повторяется, по крайней мере без нажатия на update.

**Comment by ppzhuk** [comment]
Проблема решилась дополнительной проверкой через `isAdded()`на то, привязан ли фрагмент к активити.
