### ISSUE TITLE
Проблемы с обновлением раз в час

### ISSUE THREAD

**Issue by telezhnaya** [CSC-MobDev-2016/lessson9#4]
Класс, который экстендит BroadcastReceiver, должен быть static, иначе приложение падает.
Внутри методов этого класса мы обновляем данные, то есть, нам нужен ContentResolver, чтобы слать запросы к базе. То есть, в MainActivity надо объявить static поле с ContentResolver, но статические поля - это плохо. Что делать?

**Comment by thevery** [comment]
BroadcastReceiver сам по себе Context же, то есть можно внутри просто .getContextResolver()

**Comment by telezhnaya** [comment]
Не, не получается так.
https://github.com/telezhnaya/lessson9/blob/master/app/src/main/java/com/csc/telezhnaya/weather2/MainActivity.java

В самом низу этот класс. Если его сделать static - никак не получается достать ContentResolver.

**Comment by thevery** [comment]
`public void onReceive(Context context` <- вот же!

**Comment by telezhnaya** [comment]
Мне очень стыдно. Извините
